--  Users Table
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

--  Comments Table
CREATE TABLE IF NOT EXISTS comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  text TEXT,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);


ALTER TABLE items
ADD COLUMN price DECIMAL(10, 2),
ADD COLUMN flavor VARCHAR(255),
ADD COLUMN caffeine INT,
ADD COLUMN serving_size VARCHAR(100),
ADD COLUMN calories INT,
ADD COLUMN protein DECIMAL(5, 2),
ADD COLUMN carbs DECIMAL(5, 2),
ADD COLUMN sugars DECIMAL(5, 2),
ADD COLUMN rating DECIMAL(3, 2),
ADD COLUMN review_count INT;
